#?  █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
#? █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█


# Start up services
exec-once = awww-daemon
exec-once = waybar
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = fcitx5 -d

