#?  █▀▀  █▄░█  █░█  █  █▀▄  █▀█  █▄░█  █▄ ▄█  █▀▀  █▄░█  ▀█▀
#? ██▄  █░▀█  ▀▄▀  █  █▀▄  █▄█  █░▀█  █░▀░█  ██▄  █░▀█  ░█░


# Cursor settings
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Colloid-cursors

# Theme settings
#env = GTK_THEME,Graphite-red-Dark
env = QT_QPA_PLATFORMTHEME,qt6ct


# Input method
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = SDL_IM_MODULE,fcitx

# Electron settings
env = ELECTRON_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# XWayland
env = XWAYLAND_NO_GLAMOR,1
