# --- Variáveis de Ambiente Visuais (GTK e QT) ---

# Força aplicativos GTK (Nautilus, etc) a usar o tema escuro
env = GTK_THEME,Adwaita:dark
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Define o tema para aplicativos QT (KDE, VLC, qBittorrent)
# Requer o pacote 'qt6ct' e 'qt5ct' instalados
env = QT_QPA_PLATFORMTHEME,qt6ct

# Tamanho e tema do cursor
#env = XCURSOR_THEME,Adwaita
#env = XCURSOR_SIZE,24

# --- Aparência das Janelas (Hyprland) ---

general {
    # Espaçamento entre janelas (gaps)
    gaps_in = 3
    gaps_out = 3

    # Tamanho da borda
    border_size = 2

    # Cores da borda (Ativa e Inativa)
    # Exemplo: Gradiente azul e verde
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Layout padrão (dwindle ou master)
    layout = dwindle
}

decoration {
    # Arredondamento dos cantos
    rounding = 10

    # Desfoque (Blur)
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    # Sombra
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}