#?  █░█  █  █▀▀  █░█  ▄▀█  █░░
#? ▀▄▀  █  ▄▄█  █▄█  █▀█  █▄▄

# Valores visuais padrão — sobrescritos por themes.conf
general {
	resize_on_border = false
	allow_tearing = false
}

decoration {
	active_opacity = 1
	inactive_opacity = 1
}
