#?  █░▄░█  █  █▄░█  █▀▄  █▀█  █░▄░█  █▀▀     █▀▄  █░█  █░░  █▀▀  █▀▀
#? █▀ ▀█  █  █░▀█  █▄▀  █▄█  █▀ ▀█  ▄▄█     █▀▄  █▄█  █▄▄  ██▄  ▄▄█


windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrule = opacity 0.8 0.8, match:class ^(code)$

# Steam
windowrule = float on, match:initial_class ^(steam)$, match:initial_title ^(Friends List)$
windowrule = size 300 600, match:initial_class ^(steam)$, match:initial_title ^(Friends List)$
windowrule = move bottom right, match:initial_class ^(steam)$, match:initial_title ^(Friends List)$
